extends: default

rules:
  line-length:
    max: 120
  document-start: disable
  document-end: disable
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
  empty-lines:
    max: 2
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

ignore: |
  .github/
  .terraform/
  examples/
